version: '3.11'

services:
  dashboard:
    build:
      context: .
      args:
        PDF_DIR: /Users/alex/docs/code/Odoma/pdf_extract_benchmark/resources/gotriple_pdfs
        MARKDOWN_DIR: /Users/alex/docs/code/Odoma/pdf_extract_benchmark/resources/extracted
        PAGE_SCORES_CSV: ../data/page_scores_full.csv
        METADATA_PKL: ../data/metadata_openalex\(silver\).pkl
    ports:
      - "8501:8501"
    environment:
      - PDF_DIR=/Users/alex/docs/code/Odoma/pdf_extract_benchmark/resources/gotriple_pdfs
      - MARKDOWN_DIR=/Users/alex/docs/code/Odoma/pdf_extract_benchmark/resources/extracted
      - PAGE_SCORES_CSV=../data/page_scores_full.csv
      - METADATA_PKL=./data/metadata_openalex\(silver\).pkl
    volumes:
      - ./data:/workspace/data
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 